<?php
    $models=array(
        "ActivitySummary"=>array("name"=>"销售活动(列表)",
                                 "unique"=>"0"),
        "Activity"=>array("name"=>"销售活动",
                          "unique"=>"0",
                          "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                          "add"=> array("name"=>"新增","unique"=>"1"),
                                          "edit"=> array("name"=>"编辑","unique"=>"1"),
                                          "delete"=> array("name"=>"删除","unique"=>"1"))),
        "ActivityGroupSummary"=>array("name"=>"销售活动分组(列表)",
                                      "unique"=>"0"),
        "ActivityGroup"=>array("name"=>"销售活动分组",
                               "unique"=>"0",
                               "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                               "add"=> array("name"=>"新增","unique"=>"1"),
                                               "edit"=> array("name"=>"编辑","unique"=>"1"),
                                               "delete"=> array("name"=>"删除","unique"=>"1"))),
        "AreaSummary"=>array("name"=>"地区(列表)",
                             "unique"=>"0"),
        "Area"=>array("name"=>"地区",
                      "unique"=>"0",
                      "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                      "add"=> array("name"=>"新增","unique"=>"1"),
                                      "edit"=> array("name"=>"编辑","unique"=>"1"),
                                      "delete"=> array("name"=>"删除","unique"=>"1"))),
        "BrandSummary"=>array("name"=>"品牌(列表)",
                              "unique"=>"0"),
        "Brand"=>array("name"=>"品牌",
                       "unique"=>"0",
                       "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                       "add"=> array("name"=>"新增","unique"=>"1"),
                                       "edit"=> array("name"=>"编辑","unique"=>"1"),
                                       "delete"=> array("name"=>"删除","unique"=>"1"))),
        "BuyerSummary"=>array("name"=>"买家(列表)",
                              "unique"=>"0"),
        "Buyer"=>array("name"=>"买家",
                       "unique"=>"0",
                       "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                       "add"=> array("name"=>"新增","unique"=>"1"),
                                       "edit"=> array("name"=>"编辑","unique"=>"1"),
                                       "delete"=> array("name"=>"删除","unique"=>"1"))),
        "BuyerConsigneeSummary"=>array("name"=>"买家收货人(列表)",
                                       "unique"=>"0"),
        "BuyerConsignee"=>array("name"=>"买家收货人",
                                "unique"=>"0",
                                "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                                "add"=> array("name"=>"新增","unique"=>"1"),
                                                "edit"=> array("name"=>"编辑","unique"=>"1"),
                                                "delete"=> array("name"=>"删除","unique"=>"1"))),
        "CategorySummary"=>array("name"=>"商品分类(列表)",
                                 "unique"=>"0"),
        "Category"=>array("name"=>"商品分类",
                          "unique"=>"0",
                          "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                          "add"=> array("name"=>"新增","unique"=>"1"),
                                          "edit"=> array("name"=>"编辑","unique"=>"1"),
                                          "delete"=> array("name"=>"删除","unique"=>"1"))),
        "CustomerSummary"=>array("name"=>"供应商(列表)",
                                 "unique"=>"0"),
        "Customer"=>array("name"=>"供应商",
                          "unique"=>"0",
                          "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                          "add"=> array("name"=>"新增","unique"=>"1"),
                                          "edit"=> array("name"=>"编辑","unique"=>"1"),
                                          "delete"=> array("name"=>"删除","unique"=>"1"))),
        "DeliverSummary"=>array("name"=>"配送方式(列表)",
                                "unique"=>"0"),
        "Deliver"=>array("name"=>"配送方式",
                         "unique"=>"0",
                         "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                         "add"=> array("name"=>"新增","unique"=>"1"),
                                         "edit"=> array("name"=>"编辑","unique"=>"1"),
                                         "delete"=> array("name"=>"删除","unique"=>"1"))),
        "DepartmentSummary"=>array("name"=>"部门(列表)",
                                   "unique"=>"0"),
        "Department"=>array("name"=>"部门",
                            "unique"=>"0",
                            "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                            "add"=> array("name"=>"新增","unique"=>"1"),
                                            "edit"=> array("name"=>"编辑","unique"=>"1"),
                                            "delete"=> array("name"=>"删除","unique"=>"1"))),
        "GoodsSummary"=>array("name"=>"商品信息(列表)",
                              "unique"=>"0"),
        "Goods"=>array("name"=>"商品信息",
                       "unique"=>"0",
                       "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                       "add"=> array("name"=>"新增","unique"=>"1"),
                                       "edit"=> array("name"=>"编辑","unique"=>"1"),
                                       "delete"=> array("name"=>"删除","unique"=>"1"))),
        "GroupSummary"=>array("name"=>"分组(列表)",
                              "unique"=>"0"),
        "Group"=>array("name"=>"分组",
                       "unique"=>"0",
                       "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                       "add"=> array("name"=>"新增","unique"=>"1"),
                                       "edit"=> array("name"=>"编辑","unique"=>"1"),
                                       "delete"=> array("name"=>"删除","unique"=>"1"))),
        "GroupShopSummary"=>array("name"=>"分组店铺(列表)",
                                  "unique"=>"0"),
        "GroupShop"=>array("name"=>"分组店铺",
                           "unique"=>"0",
                           "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                           "add"=> array("name"=>"新增","unique"=>"1"),
                                           "edit"=> array("name"=>"编辑","unique"=>"1"),
                                           "delete"=> array("name"=>"删除","unique"=>"1"))),
        "GroupUserSummary"=>array("name"=>"分组用户(列表)",
                                  "unique"=>"0"),
        "GroupUser"=>array("name"=>"分组用户",
                           "unique"=>"0",
                           "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                           "add"=> array("name"=>"新增","unique"=>"1"),
                                           "edit"=> array("name"=>"编辑","unique"=>"1"),
                                           "delete"=> array("name"=>"删除","unique"=>"1"))),
        "HangupTagSummary"=>array("name"=>"挂起标签(列表)",
                                  "unique"=>"0"),
        "HangupTag"=>array("name"=>"挂起标签",
                           "unique"=>"0",
                           "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                           "add"=> array("name"=>"新增","unique"=>"1"),
                                           "edit"=> array("name"=>"编辑","unique"=>"1"),
                                           "delete"=> array("name"=>"删除","unique"=>"1"))),
        "LogCommonSummary"=>array("name"=>"公用信息处理日志(列表)",
                                  "unique"=>"0"),
        "LogCommon"=>array("name"=>"公用信息处理日志",
                           "unique"=>"0",
                           "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                           "add"=> array("name"=>"新增","unique"=>"1"),
                                           "edit"=> array("name"=>"编辑","unique"=>"1"),
                                           "delete"=> array("name"=>"删除","unique"=>"1"))),
        "LogModelSummary"=>array("name"=>"模块日志(列表)",
                                 "unique"=>"0"),
        "LogModel"=>array("name"=>"模块日志",
                          "unique"=>"0",
                          "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                          "add"=> array("name"=>"新增","unique"=>"1"),
                                          "edit"=> array("name"=>"编辑","unique"=>"1"),
                                          "delete"=> array("name"=>"删除","unique"=>"1"))),
        "LogMonitorSummary"=>array("name"=>"监控日志(列表)",
                                   "unique"=>"0"),
        "LogMonitor"=>array("name"=>"监控日志",
                            "unique"=>"0",
                            "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                            "add"=> array("name"=>"新增","unique"=>"1"),
                                            "edit"=> array("name"=>"编辑","unique"=>"1"),
                                            "delete"=> array("name"=>"删除","unique"=>"1"))),
        "LogOrderSummary"=>array("name"=>"单据处理日志(列表)",
                                 "unique"=>"0"),
        "LogOrder"=>array("name"=>"单据处理日志",
                          "unique"=>"0",
                          "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                          "add"=> array("name"=>"新增","unique"=>"1"),
                                          "edit"=> array("name"=>"编辑","unique"=>"1"),
                                          "delete"=> array("name"=>"删除","unique"=>"1"))),
        "LogSalesSummary"=>array("name"=>"销售订单处理日志(列表)",
                                 "unique"=>"0"),
        "LogSales"=>array("name"=>"销售订单处理日志",
                          "unique"=>"0",
                          "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                          "add"=> array("name"=>"新增","unique"=>"1"),
                                          "edit"=> array("name"=>"编辑","unique"=>"1"),
                                          "delete"=> array("name"=>"删除","unique"=>"1"))),
        "LogStockElandSummary"=>array("name"=>"衣恋库存更新日志(列表)",
                                      "unique"=>"0"),
        "LogStockEland"=>array("name"=>"衣恋库存更新日志",
                               "unique"=>"0",
                               "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                               "add"=> array("name"=>"新增","unique"=>"1"),
                                               "edit"=> array("name"=>"编辑","unique"=>"1"),
                                               "delete"=> array("name"=>"删除","unique"=>"1"))),
        "LogWebtradeSummary"=>array("name"=>"网络订单订单处理日志(列表)",
                                    "unique"=>"0"),
        "LogWebtrade"=>array("name"=>"网络订单订单处理日志",
                             "unique"=>"0",
                             "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                             "add"=> array("name"=>"新增","unique"=>"1"),
                                             "edit"=> array("name"=>"编辑","unique"=>"1"),
                                             "delete"=> array("name"=>"删除","unique"=>"1"))),
        "NodeSummary"=>array("name"=>"模块功能(列表)",
                             "unique"=>"0"),
        "Node"=>array("name"=>"模块功能",
                      "unique"=>"0",
                      "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                      "add"=> array("name"=>"新增","unique"=>"1"),
                                      "edit"=> array("name"=>"编辑","unique"=>"1"),
                                      "delete"=> array("name"=>"删除","unique"=>"1"))),
        "OrderInterceptSummary"=>array("name"=>"订单拦截(列表)",
                                       "unique"=>"0"),
        "OrderIntercept"=>array("name"=>"订单拦截",
                                "unique"=>"0",
                                "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                                "add"=> array("name"=>"新增","unique"=>"1"),
                                                "edit"=> array("name"=>"编辑","unique"=>"1"),
                                                "delete"=> array("name"=>"删除","unique"=>"1"))),
        "OrderSwitchSummary"=>array("name"=>"转单规则(列表)",
                                    "unique"=>"0"),
        "OrderSwitch"=>array("name"=>"转单规则",
                             "unique"=>"0",
                             "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                             "add"=> array("name"=>"新增","unique"=>"1"),
                                             "edit"=> array("name"=>"编辑","unique"=>"1"),
                                             "delete"=> array("name"=>"删除","unique"=>"1"))),
        "OrderTagSummary"=>array("name"=>"标签(列表)",
                                 "unique"=>"0"),
        "OrderTag"=>array("name"=>"标签",
                          "unique"=>"0",
                          "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                          "add"=> array("name"=>"新增","unique"=>"1"),
                                          "edit"=> array("name"=>"编辑","unique"=>"1"),
                                          "delete"=> array("name"=>"删除","unique"=>"1"))),
        "PaymentSummary"=>array("name"=>"支付方式(列表)",
                                "unique"=>"0"),
        "Payment"=>array("name"=>"支付方式",
                         "unique"=>"0",
                         "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                         "add"=> array("name"=>"新增","unique"=>"1"),
                                         "edit"=> array("name"=>"编辑","unique"=>"1"),
                                         "delete"=> array("name"=>"删除","unique"=>"1"))),
        "PlatformSummary"=>array("name"=>"销售平台(列表)",
                                 "unique"=>"0"),
        "Platform"=>array("name"=>"销售平台",
                          "unique"=>"0",
                          "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                          "add"=> array("name"=>"新增","unique"=>"1"),
                                          "edit"=> array("name"=>"编辑","unique"=>"1"),
                                          "delete"=> array("name"=>"删除","unique"=>"1"))),
        "ProductSummary"=>array("name"=>"商品货号(列表)",
                                "unique"=>"0"),
        "Product"=>array("name"=>"商品货号",
                         "unique"=>"0",
                         "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                         "add"=> array("name"=>"新增","unique"=>"1"),
                                         "edit"=> array("name"=>"编辑","unique"=>"1"),
                                         "delete"=> array("name"=>"删除","unique"=>"1"))),
        "PurchaseSummary"=>array("name"=>"采购通知单(列表)",
                                 "unique"=>"0"),
        "Purchase"=>array("name"=>"采购通知单",
                          "unique"=>"0",
                          "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                          "add"=> array("name"=>"新增","unique"=>"1"),
                                          "edit"=> array("name"=>"编辑","unique"=>"1"),
                                          "delete"=> array("name"=>"删除","unique"=>"1"))),
        "PurchaseDetailSummary"=>array("name"=>"采购通知单明细(列表)",
                                       "unique"=>"0"),
        "PurchaseDetail"=>array("name"=>"采购通知单明细",
                                "unique"=>"0",
                                "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                                "add"=> array("name"=>"新增","unique"=>"1"),
                                                "edit"=> array("name"=>"编辑","unique"=>"1"),
                                                "delete"=> array("name"=>"删除","unique"=>"1"))),
        "PurchaseReturnSummary"=>array("name"=>"采购退单(列表)",
                                       "unique"=>"0"),
        "PurchaseReturn"=>array("name"=>"采购退单",
                                "unique"=>"0",
                                "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                                "add"=> array("name"=>"新增","unique"=>"1"),
                                                "edit"=> array("name"=>"编辑","unique"=>"1"),
                                                "delete"=> array("name"=>"删除","unique"=>"1"))),
        "PurchaseReturnDetailSummary"=>array("name"=>"采购退单明细(列表)",
                                             "unique"=>"0"),
        "PurchaseReturnDetail"=>array("name"=>"采购退单明细",
                                      "unique"=>"0",
                                      "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                                      "add"=> array("name"=>"新增","unique"=>"1"),
                                                      "edit"=> array("name"=>"编辑","unique"=>"1"),
                                                      "delete"=> array("name"=>"删除","unique"=>"1"))),
        "ResourceSummary"=>array("name"=>"资源库(列表)",
                                 "unique"=>"0"),
        "Resource"=>array("name"=>"资源库",
                          "unique"=>"0",
                          "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                          "add"=> array("name"=>"新增","unique"=>"1"),
                                          "edit"=> array("name"=>"编辑","unique"=>"1"),
                                          "delete"=> array("name"=>"删除","unique"=>"1"))),
        "ReturnReasonSummary"=>array("name"=>"退货原因(列表)",
                                     "unique"=>"0"),
        "ReturnReason"=>array("name"=>"退货原因",
                              "unique"=>"0",
                              "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                              "add"=> array("name"=>"新增","unique"=>"1"),
                                              "edit"=> array("name"=>"编辑","unique"=>"1"),
                                              "delete"=> array("name"=>"删除","unique"=>"1"))),
        "RoleSummary"=>array("name"=>"角色(列表)",
                             "unique"=>"0"),
        "Role"=>array("name"=>"角色",
                      "unique"=>"0",
                      "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                      "add"=> array("name"=>"新增","unique"=>"1"),
                                      "edit"=> array("name"=>"编辑","unique"=>"1"),
                                      "delete"=> array("name"=>"删除","unique"=>"1"))),
        "RoleNodeSummary"=>array("name"=>"角色模块关系(列表)",
                                 "unique"=>"0"),
        "RoleNode"=>array("name"=>"角色模块关系",
                          "unique"=>"0",
                          "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                          "add"=> array("name"=>"新增","unique"=>"1"),
                                          "edit"=> array("name"=>"编辑","unique"=>"1"),
                                          "delete"=> array("name"=>"删除","unique"=>"1"))),
        "RoleShopSummary"=>array("name"=>"角色店铺关系(列表)",
                                 "unique"=>"0"),
        "RoleShop"=>array("name"=>"角色店铺关系",
                          "unique"=>"0",
                          "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                          "add"=> array("name"=>"新增","unique"=>"1"),
                                          "edit"=> array("name"=>"编辑","unique"=>"1"),
                                          "delete"=> array("name"=>"删除","unique"=>"1"))),
        "RoleUserSummary"=>array("name"=>"角色用户关系(列表)",
                                 "unique"=>"0"),
        "RoleUser"=>array("name"=>"角色用户关系",
                          "unique"=>"0",
                          "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                          "add"=> array("name"=>"新增","unique"=>"1"),
                                          "edit"=> array("name"=>"编辑","unique"=>"1"),
                                          "delete"=> array("name"=>"删除","unique"=>"1"))),
        "SalesSummary"=>array("name"=>"销售订单(列表)",
                              "unique"=>"0"),
        "Sales"=>array("name"=>"销售订单",
                       "unique"=>"0",
                       "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                       "add"=> array("name"=>"新增","unique"=>"1"),
                                       "edit"=> array("name"=>"编辑","unique"=>"1"),
                                       "delete"=> array("name"=>"删除","unique"=>"1"))),
        "SalesConfirmSummary"=>array("name"=>"订单审单明细(列表)",
                                     "unique"=>"0"),
        "SalesConfirm"=>array("name"=>"订单审单明细",
                              "unique"=>"0",
                              "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                              "add"=> array("name"=>"新增","unique"=>"1"),
                                              "edit"=> array("name"=>"编辑","unique"=>"1"),
                                              "delete"=> array("name"=>"删除","unique"=>"1"))),
        "SalesDetailSummary"=>array("name"=>"销售订单明细(列表)",
                                    "unique"=>"0"),
        "SalesDetail"=>array("name"=>"销售订单明细",
                             "unique"=>"0",
                             "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                             "add"=> array("name"=>"新增","unique"=>"1"),
                                             "edit"=> array("name"=>"编辑","unique"=>"1"),
                                             "delete"=> array("name"=>"删除","unique"=>"1"))),
        "SalesRefundSummary"=>array("name"=>"销售退单(列表)",
                                    "unique"=>"0"),
        "SalesRefund"=>array("name"=>"销售退单",
                             "unique"=>"0",
                             "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                             "add"=> array("name"=>"新增","unique"=>"1"),
                                             "edit"=> array("name"=>"编辑","unique"=>"1"),
                                             "delete"=> array("name"=>"删除","unique"=>"1"))),
        "SalesRefundDetailSummary"=>array("name"=>"销售退单明细(列表)",
                                          "unique"=>"0"),
        "SalesRefundDetail"=>array("name"=>"销售退单明细",
                                   "unique"=>"0",
                                   "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                                   "add"=> array("name"=>"新增","unique"=>"1"),
                                                   "edit"=> array("name"=>"编辑","unique"=>"1"),
                                                   "delete"=> array("name"=>"删除","unique"=>"1"))),
        "SeasonSummary"=>array("name"=>"季节(列表)",
                               "unique"=>"0"),
        "Season"=>array("name"=>"季节",
                        "unique"=>"0",
                        "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                        "add"=> array("name"=>"新增","unique"=>"1"),
                                        "edit"=> array("name"=>"编辑","unique"=>"1"),
                                        "delete"=> array("name"=>"删除","unique"=>"1"))),
        "ServiceSummary"=>array("name"=>"系统服务(列表)",
                                "unique"=>"0"),
        "Service"=>array("name"=>"系统服务",
                         "unique"=>"0",
                         "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                         "add"=> array("name"=>"新增","unique"=>"1"),
                                         "edit"=> array("name"=>"编辑","unique"=>"1"),
                                         "delete"=> array("name"=>"删除","unique"=>"1"))),
        "ShopSummary"=>array("name"=>"店铺(列表)",
                             "unique"=>"0"),
        "Shop"=>array("name"=>"店铺",
                      "unique"=>"0",
                      "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                      "add"=> array("name"=>"新增","unique"=>"1"),
                                      "edit"=> array("name"=>"编辑","unique"=>"1"),
                                      "delete"=> array("name"=>"删除","unique"=>"1"))),
        "ShopStorageSummary"=>array("name"=>"店铺仓库(列表)",
                                    "unique"=>"0"),
        "ShopStorage"=>array("name"=>"店铺仓库",
                             "unique"=>"0",
                             "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                             "add"=> array("name"=>"新增","unique"=>"1"),
                                             "edit"=> array("name"=>"编辑","unique"=>"1"),
                                             "delete"=> array("name"=>"删除","unique"=>"1"))),
        "Stock1Summary"=>array("name"=>"商品库存(列表)",
                               "unique"=>"0"),
        "Stock1"=>array("name"=>"商品库存",
                        "unique"=>"0",
                        "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                        "add"=> array("name"=>"新增","unique"=>"1"),
                                        "edit"=> array("name"=>"编辑","unique"=>"1"),
                                        "delete"=> array("name"=>"删除","unique"=>"1"))),
        "Stock2Summary"=>array("name"=>"仓库库存(列表)",
                               "unique"=>"0"),
        "Stock2"=>array("name"=>"仓库库存",
                        "unique"=>"0",
                        "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                        "add"=> array("name"=>"新增","unique"=>"1"),
                                        "edit"=> array("name"=>"编辑","unique"=>"1"),
                                        "delete"=> array("name"=>"删除","unique"=>"1"))),
        "StockAdjustSummary"=>array("name"=>"仓库调整单(列表)",
                                    "unique"=>"0"),
        "StockAdjust"=>array("name"=>"仓库调整单",
                             "unique"=>"0",
                             "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                             "add"=> array("name"=>"新增","unique"=>"1"),
                                             "edit"=> array("name"=>"编辑","unique"=>"1"),
                                             "delete"=> array("name"=>"删除","unique"=>"1"))),
        "StockAdjustDetailSummary"=>array("name"=>"调整单明细(列表)",
                                          "unique"=>"0"),
        "StockAdjustDetail"=>array("name"=>"调整单明细",
                                   "unique"=>"0",
                                   "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                                   "add"=> array("name"=>"新增","unique"=>"1"),
                                                   "edit"=> array("name"=>"编辑","unique"=>"1"),
                                                   "delete"=> array("name"=>"删除","unique"=>"1"))),
        "StockInSummary"=>array("name"=>"仓库入库单(列表)",
                                "unique"=>"0"),
        "StockIn"=>array("name"=>"仓库入库单",
                         "unique"=>"0",
                         "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                         "add"=> array("name"=>"新增","unique"=>"1"),
                                         "edit"=> array("name"=>"编辑","unique"=>"1"),
                                         "delete"=> array("name"=>"删除","unique"=>"1"))),
        "StockInDetailSummary"=>array("name"=>"入库单明细(列表)",
                                      "unique"=>"0"),
        "StockInDetail"=>array("name"=>"入库单明细",
                               "unique"=>"0",
                               "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                               "add"=> array("name"=>"新增","unique"=>"1"),
                                               "edit"=> array("name"=>"编辑","unique"=>"1"),
                                               "delete"=> array("name"=>"删除","unique"=>"1"))),
        "StockMoveSummary"=>array("name"=>"移仓单(列表)",
                                  "unique"=>"0"),
        "StockMove"=>array("name"=>"移仓单",
                           "unique"=>"0",
                           "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                           "add"=> array("name"=>"新增","unique"=>"1"),
                                           "edit"=> array("name"=>"编辑","unique"=>"1"),
                                           "delete"=> array("name"=>"删除","unique"=>"1"))),
        "StockMoveDetailSummary"=>array("name"=>"移仓单明细(列表)",
                                        "unique"=>"0"),
        "StockMoveDetail"=>array("name"=>"移仓单明细",
                                 "unique"=>"0",
                                 "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                                 "add"=> array("name"=>"新增","unique"=>"1"),
                                                 "edit"=> array("name"=>"编辑","unique"=>"1"),
                                                 "delete"=> array("name"=>"删除","unique"=>"1"))),
        "StockMovement1Summary"=>array("name"=>"库存异动1(列表)",
                                       "unique"=>"0"),
        "StockMovement1"=>array("name"=>"库存异动1",
                                "unique"=>"0",
                                "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                                "add"=> array("name"=>"新增","unique"=>"1"),
                                                "edit"=> array("name"=>"编辑","unique"=>"1"),
                                                "delete"=> array("name"=>"删除","unique"=>"1"))),
        "StockMovement2Summary"=>array("name"=>"库存异动2(列表)",
                                       "unique"=>"0"),
        "StockMovement2"=>array("name"=>"库存异动2",
                                "unique"=>"0",
                                "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                                "add"=> array("name"=>"新增","unique"=>"1"),
                                                "edit"=> array("name"=>"编辑","unique"=>"1"),
                                                "delete"=> array("name"=>"删除","unique"=>"1"))),
        "StockOutSummary"=>array("name"=>"仓库出库单(列表)",
                                 "unique"=>"0"),
        "StockOut"=>array("name"=>"仓库出库单",
                          "unique"=>"0",
                          "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                          "add"=> array("name"=>"新增","unique"=>"1"),
                                          "edit"=> array("name"=>"编辑","unique"=>"1"),
                                          "delete"=> array("name"=>"删除","unique"=>"1"))),
        "StockOutDetailSummary"=>array("name"=>"出库单明细(列表)",
                                       "unique"=>"0"),
        "StockOutDetail"=>array("name"=>"出库单明细",
                                "unique"=>"0",
                                "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                                "add"=> array("name"=>"新增","unique"=>"1"),
                                                "edit"=> array("name"=>"编辑","unique"=>"1"),
                                                "delete"=> array("name"=>"删除","unique"=>"1"))),
        "StorageSummary"=>array("name"=>"仓库(列表)",
                                "unique"=>"0"),
        "Storage"=>array("name"=>"仓库",
                         "unique"=>"0",
                         "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                         "add"=> array("name"=>"新增","unique"=>"1"),
                                         "edit"=> array("name"=>"编辑","unique"=>"1"),
                                         "delete"=> array("name"=>"删除","unique"=>"1"))),
        "Style1Summary"=>array("name"=>"规格1(颜色)(列表)",
                               "unique"=>"0"),
        "Style1"=>array("name"=>"规格1(颜色)",
                        "unique"=>"0",
                        "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                        "add"=> array("name"=>"新增","unique"=>"1"),
                                        "edit"=> array("name"=>"编辑","unique"=>"1"),
                                        "delete"=> array("name"=>"删除","unique"=>"1"))),
        "Style2Summary"=>array("name"=>"规格2(尺码)(列表)",
                               "unique"=>"0"),
        "Style2"=>array("name"=>"规格2(尺码)",
                        "unique"=>"0",
                        "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                        "add"=> array("name"=>"新增","unique"=>"1"),
                                        "edit"=> array("name"=>"编辑","unique"=>"1"),
                                        "delete"=> array("name"=>"删除","unique"=>"1"))),
        "SystemInterfaceSummary"=>array("name"=>"系统接口参数(列表)",
                                        "unique"=>"0"),
        "SystemInterface"=>array("name"=>"系统接口参数",
                                 "unique"=>"0",
                                 "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                                 "add"=> array("name"=>"新增","unique"=>"1"),
                                                 "edit"=> array("name"=>"编辑","unique"=>"1"),
                                                 "delete"=> array("name"=>"删除","unique"=>"1"))),
        "UserSummary"=>array("name"=>"用户(列表)",
                             "unique"=>"0"),
        "User"=>array("name"=>"用户",
                      "unique"=>"0",
                      "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                      "add"=> array("name"=>"新增","unique"=>"1"),
                                      "edit"=> array("name"=>"编辑","unique"=>"1"),
                                      "delete"=> array("name"=>"删除","unique"=>"1"))),
        "WebGoodsSummary"=>array("name"=>"线上商品(列表)",
                                 "unique"=>"0"),
        "WebGoods"=>array("name"=>"线上商品",
                          "unique"=>"0",
                          "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                          "add"=> array("name"=>"新增","unique"=>"1"),
                                          "edit"=> array("name"=>"编辑","unique"=>"1"),
                                          "delete"=> array("name"=>"删除","unique"=>"1"))),
        "WebOrderDeliverSummary"=>array("name"=>"网单发货回写(列表)",
                                        "unique"=>"0"),
        "WebOrderDeliver"=>array("name"=>"网单发货回写",
                                 "unique"=>"0",
                                 "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                                 "add"=> array("name"=>"新增","unique"=>"1"),
                                                 "edit"=> array("name"=>"编辑","unique"=>"1"),
                                                 "delete"=> array("name"=>"删除","unique"=>"1"))),
        "WebProductSummary"=>array("name"=>"线上商品sku(列表)",
                                   "unique"=>"0"),
        "WebProduct"=>array("name"=>"线上商品sku",
                            "unique"=>"0",
                            "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                            "add"=> array("name"=>"新增","unique"=>"1"),
                                            "edit"=> array("name"=>"编辑","unique"=>"1"),
                                            "delete"=> array("name"=>"删除","unique"=>"1"))),
        "WebRefundSummary"=>array("name"=>"平台退单(列表)",
                                  "unique"=>"0"),
        "WebRefund"=>array("name"=>"平台退单",
                           "unique"=>"0",
                           "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                           "add"=> array("name"=>"新增","unique"=>"1"),
                                           "edit"=> array("name"=>"编辑","unique"=>"1"),
                                           "delete"=> array("name"=>"删除","unique"=>"1"))),
        "WebRefundDetailSummary"=>array("name"=>"平台退单明细(列表)",
                                        "unique"=>"0"),
        "WebRefundDetail"=>array("name"=>"平台退单明细",
                                 "unique"=>"0",
                                 "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                                 "add"=> array("name"=>"新增","unique"=>"1"),
                                                 "edit"=> array("name"=>"编辑","unique"=>"1"),
                                                 "delete"=> array("name"=>"删除","unique"=>"1"))),
        "WebTradeSummary"=>array("name"=>"平台交易(列表)",
                                 "unique"=>"0"),
        "WebTrade"=>array("name"=>"平台交易",
                          "unique"=>"0",
                          "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                          "add"=> array("name"=>"新增","unique"=>"1"),
                                          "edit"=> array("name"=>"编辑","unique"=>"1"),
                                          "delete"=> array("name"=>"删除","unique"=>"1"))),
        "WebTradeDetailSummary"=>array("name"=>"平台交易明细(列表)",
                                       "unique"=>"0"),
        "WebTradeDetail"=>array("name"=>"平台交易明细",
                                "unique"=>"0",
                                "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                                "add"=> array("name"=>"新增","unique"=>"1"),
                                                "edit"=> array("name"=>"编辑","unique"=>"1"),
                                                "delete"=> array("name"=>"删除","unique"=>"1"))),
        "YearSummary"=>array("name"=>"年份(列表)",
                             "unique"=>"0"),
        "Year"=>array("name"=>"年份",
                      "unique"=>"0",
                      "action"=>array("view"=> array("name"=>"查看","unique"=>"1"),
                                      "add"=> array("name"=>"新增","unique"=>"1"),
                                      "edit"=> array("name"=>"编辑","unique"=>"1"),
                                      "delete"=> array("name"=>"删除","unique"=>"1")))

)?>
